### ISSUE TITLE
Fix Bootstrap 5 deprecations

### ISSUE THREAD

**Issue by the-missing-pink** [coreui/coreui-pro#449]
There are two bootstrap 5 deprecated functions in core-ui-pro:

- alert-variant() | [Bootstrap Alerts](https://getbootstrap.com/docs/5.3/components/alerts/)
- list-group-item-variant() | [Bootstrap list group](https://getbootstrap.com/docs/5.3/components/list-group/#variants)

**Comment by mrholek** [comment]
CoreUI extends Bootstrap so if there is a deprecation warning in Bootstrap then it's exist also in CoreUI.

You can disable this by `$enable-deprecation-messages: false;` in your SCSS file.
